USE WWW_W10_P04_E09;

INSERT INTO GIANGVIEN (TENGV, LINHVUCNGHIENCUU, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Văn A', N'Khoa học máy tính', '0123456789', 'email01@gmail.com'),
       (N'Trần Văn B', N'Cấu trúc dữ liệu và giải thuật', '0987654321', 'email02@gmail.com'),
       (N'Lê Thị C', N'Hệ điều hành', '0654321897', 'email03@gmail.com'),
       (N'Phạm Văn D', N'Mạng máy tính', '0987123456', 'email04@gmail.com'),
       (N'Nguyễn Thị E', N'Lập trình web', '0987612345', 'email05@gmail.com');

INSERT INTO DETAI (MOTA, NAM, TENDETAI, URLHINH, MAGV) VALUES (N'Curabitur pharetra luctus erat eget volutpat. Vivamus mi nibh, maximus et imperdiet sed, ullamcorper eget lacus. Phasellus sollicitudin aliquam condimentum. Suspendisse accumsan rhoncus lorem eu interdum. Nam nibh ipsum, maximus eu enim sed, porttitor maximus mi. Suspendisse potenti. Ut tempor placerat justo, ac congue justo aliquet eu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut vitae mauris diam. Vestibulum tellus magna, sollicitudin ac ligula eu, molestie finibus ipsum. Praesent ultrices ornare neque ut faucibus. Proin et augue congue, convallis ante non, gravida enim.
Etiam lacinia nec elit eu sodales. Aenean semper est id risus scelerisque vulputate. Nam ac eros vel erat ornare posuere vitae quis lacus. In hac habitasse platea dictumst. Donec ut erat gravida, malesuada nunc eu, aliquam augue. Cras mollis eros vel sapien rhoncus varius. Aliquam id ipsum et justo dignissim ultrices. In commodo nisi nisi, in aliquet diam sagittis vitae. Donec malesuada, tortor ac luctus venenatis, tortor sem lobortis libero, id sagittis sapien leo at nunc. Maecenas a mi tincidunt, vehicula risus sed, scelerisque elit.
Nam vitae libero nec leo faucibus pulvinar eget non dolor. Proin facilisis tortor ut lorem facilisis euismod. Etiam a sapien luctus, auctor nulla sed, pulvinar lectus. Suspendisse commodo nisl magna, a varius massa commodo eu. Nam venenatis sit amet lorem at tincidunt. Aenean finibus tellus eu ligula volutpat, et sagittis ante porttitor. Nam fringilla nibh eget erat rutrum, in consectetur ex dignissim. Mauris consequat rutrum odio, at aliquet est. Aliquam quis purus rhoncus, condimentum odio ut, porta sapien. In feugiat metus quis tristique euismod. Nulla et dui eu lacus bibendum tristique a vitae eros. Praesent eleifend erat leo, a accumsan ligula sodales quis. Donec volutpat cursus elit, id pretium velit dictum eget. Aenean vestibulum tortor massa, dictum accumsan ligula molestie sed. Class aptent taciti efficitur.', 2002, N'Phân tích hiệu năng của các thuật toán học máy dựa trên mạng nơ-ron nhân tạo', N'/resources/image_DeTai/1_00001-2455295768.png', 1)
INSERT INTO DETAI (MOTA, NAM, TENDETAI, URLHINH, MAGV) VALUES (N'Quisque vitae velit iaculis sapien auctor vulputate consequat a risus. Nunc vitae augue leo. Nunc rutrum, risus a varius auctor, sapien tortor congue nisi, et vulputate mi ipsum sed ipsum. Quisque nibh eros, ornare et turpis ac, vulputate semper ligula. Integer commodo magna interdum aliquet pulvinar. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In fringilla sit amet neque non maximus. Nulla nulla magna, faucibus quis interdum ut, volutpat vel orci. Nulla vestibulum elementum efficitur. Integer nunc mauris, tempus in lorem ut, fringilla pharetra nisl. In nec lacus non tortor lobortis lobortis.
Proin egestas ex eget dolor volutpat, a condimentum mauris rhoncus. Morbi eget malesuada justo. Cras efficitur sem eget massa malesuada, quis fringilla lacus pulvinar. Nunc volutpat turpis sed odio elementum condimentum. Ut felis urna, maximus consequat varius non, lacinia eget ex. Suspendisse leo neque, lobortis sit amet feugiat id, aliquam vitae nulla. Pellentesque quis est in lacus sodales posuere in non ligula. Vestibulum ligula quam, suscipit et magna ac, lacinia auctor sapien. Sed placerat arcu sed rutrum semper. Donec dictum odio dolor, ac pulvinar nulla maximus at.
Vivamus egestas metus ligula, vel elementum mauris posuere sit amet. Fusce vel tellus odio. Ut lacinia lacus sed magna euismod pellentesque. Ut tincidunt felis at urna efficitur, blandit egestas elit tempor. Vivamus id finibus purus. Sed ac pulvinar enim. Nullam ultricies tellus enim. Nam lacus nisl, dictum vitae ipsum vitae, egestas accumsan sem. Quisque ultricies, nisl in feugiat tristique, purus quam congue ipsum, sed consectetur lectus felis et quam. Pellentesque metus tellus, sagittis quis neque sit amet, facilisis ullamcorper eros. Donec orci metus, bibendum et porta eu, feugiat in diam. Nulla sed lacus tellus. Proin dictum metus et urna imperdiet, nec efficitur neque dapibus. Maecenas egestas lectus nec leo finibus, eget pellentesque nulla blandit. Nullam feugiat imperdiet dignissim laoreet.', 2006, N'So sánh hiệu suất các cấu trúc dữ liệu cây nhị phân và AVL trong tìm kiếm', N'/resources/image_DeTai/2_00011-2060884714.png', 2)
INSERT INTO DETAI (MOTA, NAM, TENDETAI, URLHINH, MAGV) VALUES (N'Proin sed ante turpis. Maecenas venenatis est ante, mollis tincidunt ipsum pretium eget. Cras pretium tellus vel nibh luctus ultricies. Nulla vehicula nibh eget blandit pharetra. Morbi volutpat ut tortor eget cursus. Integer volutpat feugiat mauris ut aliquam. Integer fermentum feugiat turpis, quis laoreet nisi sodales non. Vestibulum eu ex et dui mattis rhoncus id ac tortor.
Mauris porta nec sem ut tincidunt. Nullam congue vel orci a maximus. Curabitur pellentesque risus ultrices, pulvinar urna sed, imperdiet arcu. Morbi facilisis suscipit enim, vitae interdum velit vulputate eu. Nulla tristique venenatis pharetra. Vestibulum molestie lorem ipsum, et rhoncus enim accumsan ut. Fusce dignissim aliquet sollicitudin. Sed hendrerit eleifend luctus. Vestibulum elementum sapien ante, quis volutpat massa dapibus at.
Pellentesque dapibus viverra nibh, sit amet ultricies felis ullamcorper sit amet. Vivamus sed pellentesque nisl, in consectetur elit. Nulla non nulla elit. Donec venenatis auctor urna nec vestibulum. Donec ultricies leo eu ex rhoncus efficitur. Aenean non imperdiet lorem. Aliquam ut libero lobortis, interdum massa ac, congue felis. Proin non tortor sed quam maximus facilisis. Sed in efficitur ante.
Nullam molestie cursus elit, et eleifend massa congue ut. Donec vitae mauris sit amet justo fringilla scelerisque. Maecenas id hendrerit sapien. Cras elementum diam id neque gravida, et consectetur lectus sollicitudin. Sed viverra congue ex, sed scelerisque magna suscipit eu. Nunc consequat est ut purus sollicitudin faucibus. Donec cursus risus sed lorem lobortis elementum a id nibh. Aliquam erat volutpat.
Nullam dapibus rutrum purus. Sed rutrum justo nisi, in ornare sapien tincidunt nec. Duis tortor odio, feugiat vitae purus in, cursus porta ligula. Proin non mi vitae massa mollis euismod sed ut urna. Nulla at quam in magna vestibulum egestas. Duis sagittis metus a est bibendum, eu congue risus eleifend. Curabitur blandit quam turpis, nec lacinia massa bibendum posuere.', 2014, N'Phân tích hiệu quả của cơ chế quản lý bộ nhớ ảo trong hệ điều hành Linux', N'/resources/image_DeTai/3_00013-2060884716.png', 3)
INSERT INTO DETAI (MOTA, NAM, TENDETAI, URLHINH, MAGV) VALUES (N'Nullam ut nisl pellentesque, maximus nibh ut, lobortis eros. Nulla sodales velit ut risus dignissim consectetur. Morbi a dignissim felis. Curabitur sit amet mi nunc. Etiam nec convallis dolor, ac aliquam purus. Pellentesque lacinia vitae nunc eu congue. Sed tempor nisl non velit facilisis, nec efficitur dolor volutpat. Praesent ac euismod mauris, sit amet sagittis urna. Donec dapibus libero augue, malesuada aliquet dui lobortis a. Morbi non egestas orci. In sed leo vel augue auctor sodales eget vitae arcu.
Aliquam eu semper erat. Ut tellus orci, venenatis a vestibulum sed, fringilla maximus tortor. Ut commodo faucibus quam, sed fringilla lacus accumsan eu. Praesent consectetur dapibus mattis. Sed volutpat magna sapien, ac scelerisque leo posuere quis. Donec eget massa hendrerit, maximus velit vel, viverra nisi. Fusce eget aliquam elit. Quisque posuere ante lorem, et commodo risus sodales vel. Sed faucibus, tortor eget scelerisque luctus, sem ex malesuada justo, at congue magna quam vitae leo. Proin mauris diam, dapibus nec scelerisque posuere, dictum id nibh.
Pellentesque vitae viverra eros, quis aliquet urna. Aliquam lorem velit, molestie id hendrerit tempus, consequat non tortor. Sed suscipit lobortis eros, eu tempor nunc. Morbi dignissim nibh a ipsum varius, ac fringilla ligula imperdiet. Aenean a tincidunt nisl. Donec fermentum gravida gravida. Curabitur sit amet metus vitae quam mollis eleifend ut tristique ligula. Morbi elit ligula, bibendum sit amet ultrices non, gravida vel mi. Donec aliquam vulputate lobortis. Nullam id velit nisi. Nulla facilisi. Sed rutrum lorem vitae ante aliquet, a dignissim enim condimentum. Nunc laoreet posuere felis id placerat.
Suspendisse potenti. Nam finibus rutrum neque non consequat. Vivamus scelerisque feugiat lectus, a aliquet nulla consectetur cursus. Integer euismod, augue eu efficitur lobortis, felis felis finibus enim, quis dapibus sem lectus sed justo. Quisque id leo vitae quam luctus convallis. Ut magna massa, viverra nisi.', 2016, N'Ứng dụng của giao thức IPv6 trong việc mở rộng không gian địa chỉ internet', N'/resources/image_DeTai/4_00017-2060884720.png', 4)
INSERT INTO DETAI (MOTA, NAM, TENDETAI, URLHINH, MAGV) VALUES (N'Sed tempor sapien vitae odio vehicula, nec tincidunt dui consectetur. Pellentesque bibendum iaculis augue, nec bibendum massa faucibus vitae. Curabitur pharetra imperdiet tristique. Integer semper massa quis magna iaculis lobortis. Sed tempus velit a mauris auctor tincidunt. Mauris et auctor orci, ut ullamcorper ante. Proin ac erat in risus lobortis commodo vitae nec justo. In ullamcorper semper sapien. Vestibulum fringilla nunc non est ultricies pharetra. Etiam non egestas nibh. Nulla malesuada facilisis pellentesque. Cras ut felis tempor, finibus est non, sollicitudin dui. Etiam bibendum, velit ut posuere elementum, dui risus rhoncus elit, eu feugiat turpis odio nec metus.
Etiam accumsan magna quis est ornare volutpat. Integer lectus tellus, mattis vel lectus id, porta sollicitudin lorem. Donec cursus ligula urna. Mauris interdum imperdiet aliquam. Nunc nec vestibulum ipsum, lacinia bibendum elit. Phasellus iaculis fermentum felis nec bibendum. Proin auctor neque id rutrum elementum. Praesent rutrum malesuada est, ac consequat neque fermentum eu. Sed non ipsum porta, tempus nunc ut, pulvinar ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam eget tellus sit amet ex sollicitudin ullamcorper. Cras fermentum quis quam nec rutrum. Aliquam congue ullamcorper ipsum quis rutrum. Suspendisse at lobortis lectus.
Integer at arcu dictum, ornare diam ut, mollis arcu. Duis consequat augue lorem, eu semper enim gravida sit amet. Aenean pellentesque finibus felis, et lacinia odio consequat id. Vivamus malesuada felis quis vulputate faucibus. Maecenas in elit euismod augue auctor placerat sed vel lectus. Sed id blandit enim. Pellentesque sit amet lorem pulvinar neque efficitur efficitur et lobortis mi. Aenean mollis dapibus tristique.
Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id risus dignissim, efficitur justo eget, imperdiet urna. In vulputate, sem id faucibus convallis, nibh ligula metus.', 2022, N'Tối ưu hóa hiệu suất và tốc độ tải trang web sử dụng kỹ thuật tối ưu hóa frontend', N'/resources/image_DeTai/5_00025-2060884728.png', 5)
